
- hosts: all
  sudo: True
  user: Vagrant
  
  tasks:
    - name: "Atualiza pacotes e instala nginx"
      apt: name=nginx state=latest update_cache=yes
      install_recommends=yes
     
 